### ISSUE TITLE
Quinn and White keyfinding?

### ISSUE THREAD

**Issue by andrewdjones** [andrewdjones/Diss_tex#1]
While setting up my sliding-window keyfinding algorithm, I use pc distribution perplexity at different time scales to choose a window size for each tune.  How do Quinn and White choose their keyfinding window sizes?  And is there a publication where they walk through their sliding windows?  @eyequeue

**Comment by eyequeue** [comment]
I'm pretty sure we explain it in the EMR article on YCAC:
http://emusicology.org/article/view/4958

**Comment by andrewdjones** [comment]
You're right, thanks -- looks like you guys implemented an 8 quarter note window and tagged each chord with the key for whatever window performed best.  I'll cite that paper in the set-up for my entropic/variable-duration key-finding windows.
